version: 2
jobs: 
  build: 
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Installing Pods...
          command: pod install
      - run:
          name: Building PockKit...
          command: xcodebuild
